git:
  branches:
  - master
  - 1.3.x
  - 1.4.x
  author:
    name: rsynek
    credentials_id: rsynek
    token_credentials_id: rsynek-gh-token
  bot_author:
    name: rsynek-bot-account
    credentials_id: rsynek-bot
  main_branch:
    default: master
maven:
  settings_file_id: 2bd418aa-56fa-4403-9232-8c77a50fc528
  nexus:
    release_url: https://repository.stage.jboss.org/nexus
    release_repository: jboss-releases-repository
    staging_profile_url: https://repository.stage.jboss.org/nexus/content/groups/kogito-public/
    staging_profile_id: 2161b7b8da0080
    build_promotion_profile_id: 1966c60aff37d
  artifacts_repository: ''
  pr_checks:
    repository:
      url: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/repositories/kogito-runtimes-pr-full-testing/
      creds_id: unpacks-zip-on-qa-nexus
cloud:
  image:
    registry_credentials_nightly: #nightly_kogito
    registry_credentials_release: #release_kogito
    registry: quay.io
    namespace: rsynek
    latest_git_branch: master
jenkins:
  email_creds_id: KOGITO_CI_EMAIL_TO
quarkus:
  lts_version: '1.11'
disable:
  triggers: false
